### ISSUE TITLE
Execute contract return  execution reverted

### ISSUE THREAD

**Issue by linyoufa** [zkSync-Community-Hub/zksync-developers#195]
https://goerli.explorer.zksync.io/tx/0xfafa411eac8ab4be493b570efbabbf9e7daf6059b6ff4b433c598fc7d31dc799

use web3j Execute contract ,return  0xfafa411eac8ab4be493b570efbabbf9e7daf6059b6ff4b433c598fc7d31dc799 has failed with status: 0x0. Gas used: 236910. Revert reason: 'execution reverted'.

**Comment by foodara90** [comment]
yaap
