### ISSUE TITLE
metamask issue

### ISSUE THREAD

**Issue by Quercitron7** [zkSync-Community-Hub/zksync-developers#282]
Hi
I have a metamask on my chrome but sadly on www.portal.zksync.io my metamask is not detected! how is it possible?

**Comment by JackHamer09** [comment]
Hey @Quercitron7, if you see "Browser Wallet" with a green checkmark then this is the option you are looking for.
<img width="388" alt="image" src="https://github.com/zkSync-Community-Hub/zksync-developers/assets/47187316/ca0bd257-ca0c-419c-a957-a80fe9d5b5eb">
