### ISSUE TITLE
Can not join zksync discord channel. 

### ISSUE THREAD

**Issue by kinqberq** [zkSync-Community-Hub/zksync-developers#295]
Hello, I have not been able to log in to the Zksync discord channel for months. After the link at [join.zksync.dev](https://join.zksync.dev/), there is a captcha confirmation phase. After saying F1rewall has invited you to join, I press the accept invitation button. It asks me to confirm "I'm human" twice with hcaptcha. Afterwards, when redirection to the zksync channel, it goes to https://discord.com/channels/@me and I cannot access the zksyn channel.

I also saw confirmation from the appeal page that I had not been banned before. please find a problem and provide a solution for me.

**Comment by oneautumnleaf98** [comment]
yes i have the same issue
oneautumn1275 is my username

**Comment by Taldaros** [comment]
i have the exact same issue, Discord username : Taldaros#2352

**Comment by 0xsisyfos** [comment]
Hello,

Thank you for reaching out to us. 

- Make sure you have a profile picture in Discord
- Make sure you do not have words such as "admin", "airdrop", etc. in your profile name.
- If you were banned, please fill out the form and we'll review as soon as we can https://appeal.zksync.dev/.

Next time, feel free to ask your question on Discord (user-support channel).

Best regards,
