### ISSUE TITLE
Unable to Join Discord channel 

### ISSUE THREAD

**Issue by polybotic** [zkSync-Community-Hub/zksync-developers#300]
Request to Add in ZKSYNC Discord channel

 User name :   poly0477

**Comment by oneautumnleaf98** [comment]
pls add me
oneautumn1275

**Comment by 0xsisyfos** [comment]
Hello,

Thank you for reaching out to us. 

- Make sure you have a profile picture in Discord
- Make sure you do not have words such as "admin", "airdrop", etc. in your profile name.
- If you were banned, please fill out the form and we'll review as soon as we can https://appeal.zksync.dev/.

Next time, feel free to ask your question on Discord (user-support channel).

Best regards,
