### ISSUE TITLE
Unable to join discord channel

### ISSUE THREAD

**Issue by Silvia789** [zkSync-Community-Hub/zksync-developers#304]
Can I have an invitation link for the discord please? (silvia0175)
Unfortunately I cannot join your discord. I tried several times via guildzksync (I have a verified level 1 and a gitcoin passport above 20 points). I don't see why it will not succeed. Please help!

**Comment by 0xsisyfos** [comment]
Hello,

Thank you for reaching out to us. 

- Make sure you have a profile picture in Discord
- Make sure you do not have words such as "admin", "airdrop", etc. in your profile name.
- If you were banned, please fill out the form and we'll review as soon as we can https://appeal.zksync.dev/.

Next time, feel free to ask your question on Discord (user-support channel).

Best regards,

**Comment by bxpana** [comment]
Please email us at [support@zksync.io](mailto:support@zksync.io) and we can help you there. This is a place for Developer support
