### ISSUE TITLE
Unable to join discord channel

### ISSUE THREAD

**Issue by mutaliperdem123** [zkSync-Community-Hub/zksync-developers#305]
My phone was stolen and I forgot everything about discord. I connected to Discord to switch to Gitcoin, but I can't join now. I've been trying every day for almost 15 days, but I couldn't get in. Please invite me to the discord channel. My username is @muto5929 please admin. 
Discord name= @muto5929

**Comment by mutaliperdem123** [comment]
@muto5929

**Comment by 0xsisyfos** [comment]
Hello,

Thank you for reaching out to us. 

- Make sure you have a profile picture in Discord
- Make sure you do not have words such as "admin", "airdrop", etc. in your profile name.
- If you were banned, please fill out the form and we'll review as soon as we can https://appeal.zksync.dev/.

Next time, feel free to ask your question on Discord (user-support channel).

Best regards,
