### ISSUE TITLE
i can't join discord

### ISSUE THREAD

**Issue by louise490** [zkSync-Community-Hub/zksync-developers#307]
please help me to join discord group again. it shows everytime ' unable to accept '

**Comment by 0xsisyfos** [comment]
Hello,

Thank you for reaching out to us. 

- Make sure you have a profile picture in Discord
- Make sure you do not have words such as "admin", "airdrop", etc. in your profile name.
- If you were banned, please fill out the form and we'll review as soon as we can https://appeal.zksync.dev/.

Next time, feel free to ask your question on Discord (user-support channel).

Best regards,
