### ISSUE TITLE
Unable to join discord

### ISSUE THREAD

**Issue by vamshidhar2205** [zkSync-Community-Hub/zksync-developers#308]
Hi zksync team..
Please help me out as Iam unable to join official discord. 
My discord username:  vamshidhar2205

**Comment by vamshidhar2205** [comment]
Team ..please find us resolve this issue. We are not able to get new updates on what is going on in the community.
Please help us join the discord

**Comment by 0xsisyfos** [comment]
Hello,

Thank you for reaching out to us. 

- Make sure you have a profile picture in Discord
- Make sure you do not have words such as "admin", "airdrop", etc. in your profile name.
- If you were banned, please fill out the form and we'll review as soon as we can https://appeal.zksync.dev/.

Next time, feel free to ask your question on Discord (user-support channel).

Best regards,
