### ISSUE TITLE
Sir provide a discord invited link🥺

### ISSUE THREAD

**Issue by warboy12** [zkSync-Community-Hub/zksync-developers#309]
Sir provide a discord invited link🥺I have been trying for a long time but can't join
![Screenshot_2024-02-04-23-40-10-412_com discord](https://github.com/zkSync-Community-Hub/zksync-developers/assets/74736531/206fcbce-41f0-4ba0-a196-f25c3c070748)

**Comment by afshan1190** [comment]
yes....i am also not able to join discord have almost tried all things...email also done

**Comment by warboy12** [comment]
> yes....i am also not able to join discord have almost tried all things...email also done

No one has replied to your emails to them

**Comment by vamshidhar2205** [comment]
They are not responding to emails and replies on twitter..not sure how to connect with them

**Comment by 0xsisyfos** [comment]
Hello,

Thank you for reaching out to us. 

- Make sure you have a profile picture in Discord
- Make sure you do not have words such as "admin", "airdrop", etc. in your profile name.
- If you were banned, please fill out the form and we'll review as soon as we can https://appeal.zksync.dev/.

Next time, feel free to ask your question on Discord (user-support channel).

Best regards,
