### ISSUE TITLE
Discord server issue

### ISSUE THREAD

**Issue by vamshidhar2205** [zkSync-Community-Hub/zksync-developers#313]
Guys let us know how should we connect with zksync team. We are not able to connect to discord server. 
We know this is a developer forum..but where is the point of contact..there is response on twitter and there is no telegram handle for resolving the issues and no response on the support emails. 

Why are you guys closing the issues..please guide us in a direction to whom to connect for support than closing the issues without resolving. It's been over a week and there is no definite way Iam able to find a solution for the discord issue. 

My discord handle: vamshidhar2205

**Comment by bxpana** [comment]
Please email us at [support@zksync.io](mailto:support@zksync.io) and we can help you there. This is a place for Developer support

**Comment by vamshidhar2205** [comment]
I emailed but there is no response..email should be from vamshidhar2205@gmail.com
