### ISSUE TITLE
unban discord Welcome to zkync-developers Discussions!

### ISSUE THREAD

**Issue by Adinurhuda** [zkSync-Community-Hub/zksync-developers#318]
### Discussed in https://github.com/zkSync-Community-Hub/zksync-developers/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **bxpana** May 24, 2023</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.
* Use the Discussions as a resource to collaborate with peers and find answers from the community. 

## ❓ Questions
The Questions Section of this Github Discussion is the perfect space for you to ask questions and seek answers from our vibrant and knowledgeable community.

Here, you'll find several categories, each dedicated to a specific topic. Whether your question pertains to SDKs, Contract Verification, Deployments, or another subject, you'll find a relevant category where you can initiate a discussion.
- [Compilers](https://github.com/zkSync-Community-Hub/zkync-developers/discussions/categories/compilers)
- [SDKs](https://github.com/zkSync-Community-Hub/zkync-developers/discussions/categories/sdks)
- [Contract Verification](https://github.com/zkSync-Community-Hub/zkync-developers/discussions/categories/contract-verification)
- [Deployments](https://github.com/zkSync-Community-Hub/zkync-developers/discussions/categories/deployments)
- [General](https://github.com/zkSync-Community-Hub/zkync-developers/discussions/categories/general)

</div> sorry sir please unban discord, i dont understand my discord ban.  
my id : 1098561155389194240 
user name : liger1008
I think the culprit is mods

**Comment by Adinurhuda** [comment]
sorry sir please unban discord, i dont understand my discord ban.  
my id : 1098561155389194240 
user name : liger1008
I think the culprit is mods

**Comment by bxpana** [comment]
@Adinurhuda please email us at support@zksync.io.
