### ISSUE TITLE
Transaction issue

### ISSUE THREAD

**Issue by bryannguyen1812** [zkSync-Community-Hub/zksync-developers#319]
Hi, i got issue of transaction, need help

**Comment by githubdoramon** [comment]
@bryannguyen1812 we definitely need more information to potentially help you. Please open a new issue providing as many details as possible. Closing this one.

**Comment by githubdoramon** [comment]
no info provided

**Comment by bryannguyen1812** [comment]
I did a bridge from Zksync Era Mainnet to Ethereum Mainnet with ETH, but it is not completed transaction for nearly 1 hour. My zksync wallet was deducted token ETH already. Pls help
Here is my hash: 0xa1c30700de66d46a536572a1dad0b5e4e6b8cc29db476272b95a90ef2f223048
