### ISSUE TITLE
404 errors about README.md's link

### ISSUE THREAD

**Issue by zssbecker** [zkSync-Community-Hub/zksync-developers#329]
On zksync-developers's README.md;
https://github.com/zkSync-Community/zksync-community/blob/70e728d5906adcf7efd87f3f06277a6001bb498b/Content/What%20is%20the%20difference%20between%20zkSync%20Lite%20and%20zkSync%20Era%3F.md

There is 404 error now, sir.
Firfox and chrome., edge also.

**Comment by Kimchikim12** [comment]
It seems to be the case still.

**Comment by bxpana** [comment]
Got that fixed now and updated the readme
