### ISSUE TITLE
verified level 2 with guild.xyz

### ISSUE THREAD

**Issue by mnuww** [zkSync-Community-Hub/zksync-developers#345]
i hope can change verified not just with guild but with other because is hard for some people to verified in guild

**Comment by richyempir** [comment]
I think it is  an issue with guild ratings, but to make your verification fast, use mobile and connect to any web3  wallets. Sign in and check access on discord it will work out good

**Comment by msakhaei** [comment]
Hello, I can't join to discord so I can't be qualified for level 2.
​

**Comment by nguyenngocsy** [comment]
Tôi không thể kết nối ví metamask với bang hội

**Comment by nguyenngocsy** [comment]
I can't connect the metamask wallet to the guild

**Comment by traderworld** [comment]
the issue is resolved for me be patient the team is working

**Comment by msakhaei** [comment]
Glad to hear it!
Thanks

**Comment by shivsantosh1996** [comment]
I am also unable to join in discord. Kindly resolve my issue and allow me join into discord. 

![1](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/878191b4-a664-40fe-9644-c13af9cb4a6f)
![2](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/09ff3fb1-1ad6-414f-9eeb-bd8ffc454eae)
![3](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/cf1150b9-5ac8-4493-ab42-4b9825ea2f99)

**Comment by shivsantosh1996** [comment]
I am also unable to join in discord. Kindly resolve my issue and allow me join into discord. I am requesting ZkSync members kindly look into this matter.

![1](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/7cb91add-f94e-465d-8f86-1f58184c3882)
![2](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/5cc16f19-a041-4574-b19c-63a3dd7792dd)
![3](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/8d912c93-c419-45b2-a851-379985403a04)
