### ISSUE TITLE
Multi language + Dark mode in mobile explorer 

### ISSUE THREAD

**Issue by Speedevs** [zkSync-Community-Hub/zksync-developers#347]
Already explained what should be added here

https://github.com/matter-labs/block-explorer/issues/178

On the GitHub page.

Decided to post it here ,to prevent people from repeating the post

**Comment by JackHamer09** [comment]
Thanks for request. No need to duplicate it.

**Comment by Speedevs** [comment]
Ohk my bad sorry 🫡
