### ISSUE TITLE
join to discord

### ISSUE THREAD

**Issue by msakhaei** [zkSync-Community-Hub/zksync-developers#353]
Hello, I can't join to discord so I can't be qualified for level 2.
​

**Comment by shexinyi321** [comment]
I am also can't join to discord so

**Comment by shivsantosh1996** [comment]
I am also unable to join in discord. Kindly resolve my issue and allow me join into discord.
![2](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/918d23a4-57a1-4d76-83a4-f68372b23a5a)
![1](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/b77b5229-aba6-470f-afd0-86869bc80861)
![3](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/b58560f0-55c5-42f6-ab71-ff032b2ee157)

**Comment by shivsantosh1996** [comment]
I am also unable to join in discord. Kindly resolve my issue and allow me join into discord.

![1](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/587557a1-5074-4e0b-ad41-959ee68652e8)
![2](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/03897ab1-0faf-4bf3-b1b8-3ee133f98c22)
![3](https://github.com/zkSync-Community-Hub/zksync-developers/assets/43996335/fcb9a0dc-e102-443f-96f1-b76f9b335173)

**Comment by yarikMyroniuk** [comment]
How can I join to discord?

**Comment by bxpana** [comment]
For all issues regarding Discord please email us at support@zksync.io
