### ISSUE TITLE
Contract verification fails with zksolc 1.4.0

### ISSUE THREAD

**Issue by dextfprotocol** [zkSync-Community-Hub/zksync-developers#382]
I have a script to deploy and verify a contract to zkSync Sepolia.

Initially my `package.json` contained the following:

```
    "@matterlabs/hardhat-zksync-deploy": "1.2.0",
    "@matterlabs/hardhat-zksync-solc": "1.1.4",
    "@matterlabs/hardhat-zksync-verify": "1.4.0",
    "hardhat": "2.20.1",
    "solc": "0.8.24",
```

And my `hardhat.config.ts` these:

```
  zksolc: {
    version: "1.4.0", // Uses latest available in https://github.com/matter-labs/zksolc-bin/
    settings: {},
  },
  solidity: {
    version: "0.8.24",
    settings: {
      optimizer: {
        enabled: true,
        runs: 300,
      },
    },
  },
  defaultNetwork: "zkSyncTestnet",
  networks: {
    sepolia: {
      url: "https://sepolia.infura.io/v3/<key>", // The Ethereum Web3 RPC URL (optional).
      zksync: false, // disables zksolc compiler
    },
    zkSyncTestnet: {
      url: "https://sepolia.era.zksync.dev/", // The testnet RPC URL of zkSync Era network.
      ethNetwork: "sepolia", // The Ethereum Web3 RPC URL, or the identifier of the network (e.g. `mainnet` or `goerli`)
      zksync: true, // enables zksolc compiler
      verifyURL: "https://explorer.sepolia.era.zksync.dev/contract_verification",
    },
```

The verification is done with:

```
  const verificationId = await hre.run("verify:verify", {
    address: contractAddress,
    contract: contractFullyQualifedName,
    constructorArguments: constructorArguments
  });
```
where `constructorArguments` is the same array successfully used few lines before to deploy.

The verification fails with the latest `zksolc 1.4.0` and `solc 0.8.24` with error `Error in plugin @matterlabs/hardhat-zksync-verify: Backend verification error: Deployed bytecode is not equal to generated one from given source`.

I tried to keep `zksolc 1.4.0` and downgraded the `solc` version to `0.8.23`, `0.8.22` and `0.8.21`, but the verification keeps failing.

Eventually, to make it work, I had to downgrade to `zksolc 1.3.23` with `solc 0.8.23`.

**Comment by uF4No** [comment]
hey @dextfprotocol please move this to [the discussions section](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/categories/contract-verification) and we'll try to help there

**Comment by dextfprotocol** [comment]
I already found a workaround myself.
This was to report the issue with `zcsolc 1.4.0` as suggested in a separate chat in Discord, to allow the dev team to fix it.

**Comment by dextfprotocol** [comment]
@uF4No could you re-open the issue please?

**Comment by dextfprotocol** [comment]
great news! Thanks for the quick turnaround!

**Comment by dextfprotocol** [comment]
Unfortunately it does does not work - see https://github.com/zkSync-Community-Hub/zksync-developers/issues/388
