### ISSUE TITLE
LIBERTAS OMNIBUS NFT FORM

### ISSUE THREAD

**Issue by morgannordahl** [zkSync-Community-Hub/zksync-developers#408]
I have a libertas omnibus nft and I am trying to fill out the form. I have tried both chrome and edge and neither have worked. I tried two computers and my phone. I tried clearing the cache. I tried refreshing the page. It just keeps saying the same thing over and over: 
 "form submission failed. please try again later. " someone said maybe your nft is on a different account. I only have one account. Someone please help. Thanks. 
![libertas](https://github.com/zkSync-Community-Hub/zksync-developers/assets/75652164/51e1eec1-9c0e-4beb-8dba-a0ae935a3266)

**Comment by bxpana** [comment]
Which form are you talking about?

**Comment by morgannordahl** [comment]
It's this form

https://libertas.summon.xyz/

**Comment by bxpana** [comment]
@morgannordahl I have not seen that form so I would reach out to the Summon team (https://summon.xyz/) to verify if it is real or a scam
