### ISSUE TITLE
[bug] dead link 

### ISSUE THREAD

**Issue by fuchanghai** [zkSync-Community-Hub/zksync-developers#411]
<img width="1326" alt="image" src="https://github.com/zkSync-Community-Hub/zksync-developers/assets/33984497/8cc790c9-ce1e-4e9f-8c94-44b76231ae03">

**Comment by MildSandy** [comment]
VERY Good 🙂

**Comment by bxpana** [comment]
@fuchanghai thanks, fixed that and updated the readme
