### ISSUE TITLE
bug transfer

### ISSUE THREAD

**Issue by XiaoLannn** [zkSync-Community-Hub/zksync-developers#418]
I just made a transfer from my spot wallet to web3 wallet via zkSync, it's just that there is a problem where the transfer status is completed but the token doesn't go to the destination address, and after I checked via blockchain explorer it turns out the token is still in sending status, I've been waiting for 20 minutes but it's still the same, this is the first time I've tried this network, it's just quite disappointing, maybe someone here can help me with this problem?

**Comment by JackHamer09** [comment]
Usually simple token transfers take just few seconds to complete.

You need to provide more details for us to be able to assist you.
- Share your transaction hash if you're comfortable with that.
- What do you mean by Spot wallet? Did you transfer funds from your exchange account?
- Where do you see that the "transfer status is completed" and where do you see that it's "still sending"?

**Comment by XiaoLannn** [comment]
i do from my bnb spot wallet to web3 wallet, it take more than 1h, but
still same, no token received, even though the status is "completed" in my
wallets

Pada Sel, 19 Mar 2024 15.12, Jack Hamer ***@***.***> menulis:

**Comment by XiaoLannn** [comment]
is it normal 7h for 1 transaction? idk that the problem from zksync or eth,
but it hasn't been finished till now

Pada Sel, 19 Mar 2024 15.20, Imam MF ***@***.***> menulis:

**Comment by JackHamer09** [comment]
@XiaoLannn when doing a withdrawal from your exchange account, are you sure you've selected "zkSync Era" as the destination network?
- If you've selected a different chain then you should be able to find your tokens there.
- If you're sure you selected a correct chain then you should seek help from the exchange support.

**Comment by XiaoLannn** [comment]
https://explorer.zksync.io/tx/0x2dc0e1e9023b4a2d59208b5cf71aeca8f5484153f84ec447b92667b5efbba788

mybe u can check it

Pada Sel, 19 Mar 2024 15.32, Jack Hamer ***@***.***> menulis:

**Comment by XiaoLannn** [comment]
it same even when I tried the opposite, u can check it anyway

0xe1e1a52e35eaeb25e751fb0ee4374233300f45c12439587022683b81a529696d



Pada Sel, 19 Mar 2024 22.01, Jack Hamer ***@***.***> menulis:

**Comment by JackHamer09** [comment]
@XiaoLannn in the new transaction hash that you shared the destination address is different but I don't see any problem with that transaction. Please, see my previous message for info.
