### ISSUE TITLE
Guild Role

### ISSUE THREAD

**Issue by ShiniAmalTyagi** [zkSync-Community-Hub/zksync-developers#424]
Dont receive role in discord level1 
![image_2024-03-24_165317757](https://github.com/zkSync-Community-Hub/zksync-developers/assets/87266834/24efb259-faee-489c-a172-27610cb48561)
<img width="957" alt="2" src="https://github.com/zkSync-Community-Hub/zksync-developers/assets/87266834/f70cc98d-1c39-4357-a8cf-e484bbd4434b">

**Comment by bxpana** [comment]
Please email us at support@zksync.io regarding this issue
