### ISSUE TITLE
[General] paymaster <Title>

### ISSUE THREAD

**Issue by omidkhanaki** [zkSync-Community-Hub/zksync-developers#438]
when we are using paymaster most wallets showing alarm about high risk transaction. sometimes when using new dapps we realy afraid about using paymaster. if it there is nothing to concern so make a solution for dapps or wallets to solve this problem and making us feeling safe

**Comment by bxpana** [comment]
@omidkhanaki let's move this over to the [Discussions](https://github.com/zkSync-Community-Hub/zkync-developers/discussions) so we can get some more details about what's going on.
