### ISSUE TITLE
Paymaster transaction fail

### ISSUE THREAD

**Issue by yurymarozau** [zkSync-Community-Hub/zksync-developers#440]
Hello!
Transaction hash: 0xd830b99982f237f2faa7e74337097604d69d8c3f9d0e33de522a3e3035a30aa3
Link: https://era.zksync.network/tx/0xd830b99982f237f2faa7e74337097604d69d8c3f9d0e33de522a3e3035a30aa3
Transaction fails if I use USDT as gas on https://syncswap.xyz/ and swap 100% of my USDT to ETH.
Is this behavior expected or not (or such cases should handle platforms that use paymaster)?

**Comment by bxpana** [comment]
@yurymarozau this sounds like something to reach out to syncswap about. If this is a developer specific question you can open up a [discussion](https://github.com/zkSync-Community-Hub/zkync-developers/discussions) with the necessary details.
