### ISSUE TITLE
Open ports

### ISSUE THREAD

**Issue by rocketport** [zkSync-Community-Hub/zksync-developers#532]
<img width="1265" alt="Monosnap Termius - ZKSYNC_NODE 2024-05-16 13-22-39" src="https://github.com/zkSync-Community-Hub/zksync-developers/assets/34209929/b62420fc-c5d6-4a23-9f68-cf481b5b971e">

The node gained altitude - but port 80 is closed. same as 3060 and 3000. I tried to open it manually via ufw - but RPC still doesn't work.

**Comment by bxpana** [comment]
If you're still having issues please open up a discussion post so we can get all the necessary information https://github.com/zkSync-Community-Hub/zkync-developers/discussions
