### ISSUE TITLE
Problem with deposit

### ISSUE THREAD

**Issue by Vein82** [zkSync-Community-Hub/zksync-developers#546]
Hi there I have sent usdt to my metamusk from binance and just cant find it some stuff from meta told me to change network and it still doesnt help Zksynk Lite still showing 0usdt and he said to talk to u may need to add network mannually but its too difficult for me can u refund this payment I will stay on bibyt.
My withdrawall adress is: 0xC57d3b821d16156c37bC161442141dCf14091f1F
My TXID: 0xfa7cd79078bc11234847ab7db332573ea9fbe53d6a78ed395eba0ba1297c4217

**Comment by bxpana** [comment]
For issues regarding deposits please email us at support@zksync.io and we can help you there. This is for developer related issues. Thanks!
