### ISSUE TITLE
Sepolia transactions occasionally failing

### ISSUE THREAD

**Issue by MichaelSheinman** [zkSync-Community-Hub/zksync-developers#547]
Hi there, I am seeing an issue with sepolia transaction occasionally failing with an error "Error function_selector = 0x, data = 0x". This happens approximately once for every 50 transactions I send to the network. 

Example transactions: 
https://sepolia.explorer.zksync.io/tx/0x7183effad349b128ef82d58eb27e6b5cdcd2d4f02ae37c8cf582a83136db1345
https://sepolia.explorer.zksync.io/tx/0xf9fb1d51b4492b288eade87f310a15c912439e3d7d52e3cc67a3953a98f2a5d6

I heard this issues tends to indicate gas problem, however we are using the `eth_gasPrice` and the `eth_estimateGas` RPC calls for the gas estimation, and we are also adding a buffer on these values for extra caution.

Expected behaviour would be either that the transaction fails with some error message when I send the transaction, or that the transaction succeeds. However, the current behaviour is that the sending part of the transaction goes through and then the transaction fails.

**Comment by bxpana** [comment]
@MichaelSheinman could you please open up a discussion post instead so more people can contribute/see what the solution is once it's resolved? https://github.com/zkSync-Community-Hub/zkync-developers/discussions

**Comment by MichaelSheinman** [comment]
done https://github.com/zkSync-Community-Hub/zksync-developers/discussions/548
