### ISSUE TITLE
Request for Airdrop Review

### ISSUE THREAD

**Issue by Magadan922** [zkSync-Community-Hub/zksync-developers#577]
Dear zkSync Support Team,

I hope this message finds you well. I am writing to inquire about the recent airdrop. Despite my active and long-term participation in the zkSync ecosystem, I did not receive the airdrop. I have made numerous transactions and have been a consistent contributor.

Could you please review my wallet and check if there was an oversight? My wallet address is [ 0x973e2b8dBC12DE549213cc83e732A755bFe350d8 ]. I would greatly appreciate it if you could look into this matter and provide me with any information or assistance.

Thank you for your time and support.

Best regards,

**Comment by bxpana** [comment]
Hello,

Thank you for reaching out.

The ZK Token FAQ provides additional details on eligibility criteria: https://docs.zknation.io/zk-token/zk-token-faq

In particular, question 3 ("I met some of the eligibility criteria, but did not get an allocation, why not?") answers your question directly.

As a note, this space if for developer questions, please join the Discord for further support: https://join.zksync.dev/
