### ISSUE TITLE
A sincere request to check the address to Airdrop eligibility

### ISSUE THREAD

**Issue by mat56ghj** [zkSync-Community-Hub/zksync-developers#581]
Dear zkSync Support Team,

I hope this message finds you well. I am writing to inquire about the recent airdrop. Despite my active and long-term participation in the zkSync ecosystem, I did not receive the airdrop. I have a Libertas Omnibus since it dropped to users. I have also roles on discord but my allocation actually is 0. I have made numerous transactions and have been a consistent contributor. I will attach some proofs below.

Could you please review my wallet and check if there was an oversight? 
My wallet address is [ 0x49E4c5B22f26C02fD8E4E6680f1594dE45720405 ]. I would greatly appreciate it if you could look into this matter and provide me with any information or assistance.

Thank you for your time and support.

Best regards, Mateo
![LIBERTAS-OMNIBUS](https://github.com/zkSync-Community-Hub/zksync-developers/assets/150865283/5246d769-0586-44ea-9a6c-2f877badc198)
![Zrzut ekranu 2024-06-11 162341](https://github.com/zkSync-Community-Hub/zksync-developers/assets/150865283/5b6de4a4-0d27-4789-9f7c-566f945955e2)
![ZkFlow (1)](https://github.com/zkSync-Community-Hub/zksync-developers/assets/150865283/77c81cef-42ed-4343-9d82-60b55d021123)

**Comment by mat56ghj** [comment]
![zkSync-Airdrop-Rank-Checker](https://github.com/zkSync-Community-Hub/zksync-developers/assets/150865283/5e2dbc29-87b9-4b68-9ee1-511ae3c9f965)

**Comment by mat56ghj** [comment]
The NFT libertas omnibus i bought 2023-08-20 14:28 Transaction below
https://explorer.zksync.io/tx/0x69b578646e0d93003cbb3b0b56055d3e534e2553df79e78460d90d896ab307a5

Snapshot was 24 March 2024.  I'm using only one wallet. I'm confused. 

Hope you would read and respond. 
Regards
![LIBERTAS-OMNIBUS (1)](https://github.com/zkSync-Community-Hub/zksync-developers/assets/150865283/543a150a-dacd-44bb-8570-deca976b1b48)

**Comment by bxpana** [comment]
Hello,

Thank you for reaching out.

The ZK Token FAQ provides additional details on eligibility criteria: https://docs.zknation.io/zk-token/zk-token-faq

In particular, question 3 ("I met some of the eligibility criteria, but did not get an allocation, why not?") answers your question directly.

As a note, this space if for developer questions, please join the Discord for further support: https://join.zksync.dev/
