### ISSUE TITLE
Why I’m not eligible? I have only one Wallet

### ISSUE THREAD

**Issue by Berkay6600** [zkSync-Community-Hub/zksync-developers#586]
I am deeply shocked, I have been farming for months, fulfill all the criteria, Gitcoim well over 20 points and have been doing that for 6 months, always had over 0.01 Eth in my wallet and above all I only have one wallet, put all my money in it and now nothing, do you have a clear conscience?

![IMG_0471](https://github.com/zkSync-Community-Hub/zksync-developers/assets/147265761/53f49113-78a1-4dd0-b9c4-deb69d42d473)
![IMG_0472](https://github.com/zkSync-Community-Hub/zksync-developers/assets/147265761/3af73d03-5211-4b4c-b2d4-e74c24f0abcb)
![IMG_0473](https://github.com/zkSync-Community-Hub/zksync-developers/assets/147265761/66ed3af5-4d22-45c8-9698-9e5eba538097)
![IMG_0477](https://github.com/zkSync-Community-Hub/zksync-developers/assets/147265761/8bf93414-1ade-4158-967d-6a731e3a7556)

**Comment by bxpana** [comment]
Hello,

Thank you for reaching out.

The ZK Token FAQ provides additional details on eligibility criteria: https://docs.zknation.io/zk-token/zk-token-faq

In particular, question 3 ("I met some of the eligibility criteria, but did not get an allocation, why not?") answers your question directly.

As a note, this space if for developer questions, please join the Discord for further support: https://join.zksync.dev/
