### ISSUE TITLE
iligiable for airdrop

### ISSUE THREAD

**Issue by 5976madhav5976** [zkSync-Community-Hub/zksync-developers#589]
why i am not eligiable for airdrop i am doing all task step by step 
kindly chek my wallet 0x6e30f13f816FE2D991CE2Fc8a118b16cCD9dB754  
and let me know what is the issu

**Comment by hackspaceit** [comment]
Same, my address not eligible for airdrop 0xaa66fc4433dfd254f05a720a8c8a2f1f2fbdcb58
![Screenshot (149)](https://github.com/zkSync-Community-Hub/zksync-developers/assets/132249505/8093e8d3-b4f4-40da-8992-3bf904577a92)

**Comment by bxpana** [comment]
Hello,

Thank you for reaching out.

The ZK Token FAQ provides additional details on eligibility criteria: https://docs.zknation.io/zk-token/zk-token-faq

In particular, question 3 ("I met some of the eligibility criteria, but did not get an allocation, why not?") answers your question directly.

As a note, this space if for developer questions, please join the Discord for further support: https://join.zksync.dev/
