### ISSUE TITLE
Support for Foundry-ZkSync in discussion

### ISSUE THREAD

**Issue by L0GYKAL** [zkSync-Community-Hub/zksync-developers#617]
It would be great to have a section for Foundry-ZkSync in discussions

**Comment by bxpana** [comment]
We could work on adding that. What way do you think that would make things more efficient for ZKsync Foundry instead of posting in the tools section?

**Comment by L0GYKAL** [comment]
I've redirected there by a member of the ZkSync team after having problems with Foundry and I found out, it only supports Hardhat, so I thought it might be great to have support for Foundry.
![image](https://github.com/zkSync-Community-Hub/zksync-developers/assets/32228897/42e6a7e1-a324-4388-aef2-810a31d8645d)
![image](https://github.com/zkSync-Community-Hub/zksync-developers/assets/32228897/f93cd487-5a5f-4a2a-8978-d42c5c653245)

**Comment by bxpana** [comment]
Ah I see what you mean, we could add a foundry option for when providing information to your posts. Good suggestion
