### ISSUE TITLE
Dear ZKSync Support Team

### ISSUE THREAD

**Issue by Bokigti** [zkSync-Community-Hub/zksync-developers#634]
I hope this message finds you well. I am writing to address an issue with my airdrop eligibility. According to ZKFlow, I am eligible to receive 6250 ZK tokens. However, on your official ZKSync airdrop page, it states that I am not eligible.
I have been actively using ZKSync for 467 days ago, executing multiple transactions. Could you please review my account and clarify this discrepancy?

Thank you for your assistance.

Best regards,
Slobodan

**Comment by bxpana** [comment]
Please see your other discussion post for the answer. https://github.com/zkSync-Community-Hub/zksync-developers/discussions/635
