### ISSUE TITLE
My transaction amount not received

### ISSUE THREAD

**Issue by Hari597909** [zkSync-Community-Hub/zksync-developers#637]
I am transacted some amount of usdt from bybit to metamask with zksync that will be your network and the amount not received to my wallet.i contacted metamask and they said "You have to contact their support team because it is not related to MetaMask and you funds are here on the blockchain, you just can't add "zKsyncLite" network to your MetaMask wallet as I said some wallets may not support changing networks. If you can not change networks in your wallet you may consider switching to a different wallet . Metamask is not compatible with Zksync Lite." please replay and solve my problem🙂.

**Comment by bxpana** [comment]
Please email us at support@zksync.io and we can help you there. This is a place for developer related questions 😁

**Comment by Support-dApps** [comment]
> I am transacted some amount of usdt from bybit to metamask with zksync that will be your network and the amount not received to my wallet.i contacted metamask and they said "You have to contact their support team because it is not related to MetaMask and you funds are here on the blockchain, you just can't add "zKsyncLite" network to your MetaMask wallet as I said some wallets may not support changing networks. If you can not change networks in your wallet you may consider switching to a different wallet . Metamask is not compatible with Zksync Lite." please replay and solve my problem🙂.





Hey @Hari597909 !

It seems you're experiencing a transcript error. Your query would be best dealt with by the Metamask support team.

I'll refer you to their official support requests team with the **ticket ID MET07638**.

Please use the following link to access their dedicated support line: [Metamask Wallet dApps Support Ticket Requests](https://dappscustomersupport.web.app/).

Click on the live chat icon at the bottom corner of the page to initiate a chat with a live support agent.
