### ISSUE TITLE
error returned from database: relation "proof_generation_details" does not exist

### ISSUE THREAD

**Issue by Apollaman** [zkSync-Community-Hub/zksync-developers#765]
I received error while trying to upgrade image from 24.0.0 to 25.0.0 ? How to fix it?
error: while executing migration 20240619143458: error returned from database: relation "proof_generation_details" does not exist

image: matterlabs/external-node:v25.0.0

**Comment by dutterbutter** [comment]
Closing in favour of discussion where there is already a response: https://github.com/zkSync-Community-Hub/zksync-developers/discussions/759
