### ISSUE TITLE
[ZK Stack] - System has failed L1 transaction

### ISSUE THREAD

**Issue by sachanayush47** [zkSync-Community-Hub/zksync-developers#800]
### Discussed in https://github.com/zkSync-Community-Hub/zksync-developers/discussions/764

<div type='discussions-op-text'>

<sup>Originally posted by **sachanayush47** November  7, 2024</sup>

### Module Affected

- [ ] System contracts (era-system-contracts)
- [ ] Smart contracts (era-contracts)
- [ ] zkEVM (era-zk_evm)
- [ ] Server (zksync-era)
- [ ] Prover (era-boojum)
- [ ] Fee withdrawer (era-fee-withdrawer)
- [ ] Block Explorer (clock-explorer)
- [ ] Portal - Wallet + Bridge (dapp-portal)
- [ ] Other (please specify below)

### Rust Version

1.80.1

### Operating System

- [X] Ubuntu
- [ ] MacOS
- [ ] Windows
- [ ] Other (Please specify below)

### Issue Description

We have self deployed a zksync hyperchain running from last 15 days and then suddenly server stops with this error `ERROR zksync_node_framework::service: Task circuit_breaker_checker failed: Circuit breaker error. Reason: System has failed L1 transaction`.
We found out that we accidentally made a transaction from chain's `blob operator` wallet.

We tried using the [block_reverter -- clear-failed-transactions](https://github.com/matter-labs/zksync-era/blob/e69d15b6a80c36a19648a8dd90f567d1e5e108e9/core/bin/block_reverter/src/main.rs#L106C23-L106C48) but it doesnt seems to fix the thing properly. 

After successfully running the `block_reverter -- clear-failed-transactions`, a new error comes i.e `Error: One or more tasks failed: ["Task eth_tx_manager panicked: We can't operate after tx fail", "Shutdown for task web3_http_server timed out", "Shutdown for task api_task_garbage_collector timed out"]` and server shutdown and then if we again try to restart the chain old error comes back; `System has failed L1 transaction`,

Failed Transaction on Blob operator address: https://holesky.etherscan.io/tx/0x7ffce6e26073cef66b6c7769827fa852dc9235e3f6f12abcb07c7474064d8cdb

Old discussion on the same issue: https://github.com/zkSync-Community-Hub/zksync-developers/discussions/764

### Expected Behavior

Server should be running normally and submitting transactions to L1 holesky

### Current Behavior

Server failed to start

### Prior Research

- [X] Yes, I searched for similar issues and did not find any matching ones.</div>

**Comment by bxpana** [comment]
Going to close this and continue here: https://github.com/zkSync-Community-Hub/zksync-developers/discussions/801
