### ISSUE TITLE
Zk tokens funds have not credited  from Binance to my  wallet yet

### ISSUE THREAD

**Issue by Papaflash88** [zkSync-Community-Hub/zksync-developers#846]
hello, i withdrawal from Binance to the Zksync network, but the funds have not credited to my  wallet  yet, Based on the transaction ID , it appears this withdrawal was sent to the Zksync network, what should i do now?

**Comment by Saoiray405** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by KlamdeMo-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [zkSyn Support](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Sandeep8765** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by kaymomin** [comment]
Please direct this issue to Binance support. Thank you!
